### ISSUE TITLE
Release of eventlog

### ISSUE THREAD

**Issue by mochrul** [balabit/eventlog#1]
Is eventlog still a dependency for syslog-ng? Is there any official (current) release of eventlog?

Maybe I'm wrong, but the highest version of eventlog is 0.2.13 which is in this repo, but there are no release from this. Is there any plan to release eventlog?

**Comment by bazsi** [comment]
Hi,

honestly, this should be folded back into the syslog-ng source tree, which
has not yet been done. I don't know about any other user of eventlog in
other projects, so this one should be discontinued.

Simply it has not yet happened, as we had other more important tasks to be
done, but merging this back into syslog-ng would be a great contribution :)
(hint, hint :)

Bazsi

## 

Bazsi

**Comment by MrAnno** [comment]
`eventlog` (`libevtlog`) has been merged into syslog-ng.

I'm closing this issue.
