### ISSUE TITLE
Provide a working release source tarball download

### ISSUE THREAD

**Issue by tgurr** [balabit/eventlog#3]
Currently there seems no way to get a release source tarball of eventlog as http://www.balabit.com/downloads/files/eventlog/0.2/eventlog_0.2.13.tar.gz redirects to oneidentity.com. It would be nice to have them added on Github as well like done for syslog-ng.

**Comment by MrAnno** [comment]
Hi,

`eventlog` has been merged into [balabit/syslog-ng](https://github.com/balabit/syslog-ng), it is not available as a separate library anymore.

**Comment by tgurr** [comment]
@MrAnno thanks for that information, shouldn't https://github.com/balabit/eventlog/issues/1 be closed then as well?

**Comment by MrAnno** [comment]
You are absolutely right, I've closed it :)
